import type { Metadata } from "next";
import { radioCanada, spaceGrotesk } from "./components/fonts";
import { NavBar } from "./components/nav-bar";
import { SideBar } from "./components/side-bar";
import { ThemeProvider } from "./components/theme-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${spaceGrotesk.className} ${radioCanada.variable} antialiased bg-background text-foreground flex `}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SideBar.Root />
          <div className="h-full w-[250px] hidden md:block"></div>
          <div className="flex-1 flex flex-col">{children}</div>
          <NavBar.Root />
        </ThemeProvider>
      </body>
    </html>
  );
}
