import type { Metadata } from "next";
import { radioCanada, spaceGrotesk } from "./components/fonts";
import { NavBar } from "./components/nav-bar";
import SideBarRoot from "./components/side-bar/side-bar-root";
import { ThemeProvider } from "./components/theme-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} ${radioCanada.variable} antialiased bg-background text-foreground flex`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <SideBarRoot />
          {children}
          <NavBar.Root />
        </ThemeProvider>
      </body>
    </html>
  );
}
